### ISSUE TITLE
Open folder only once when taking all devices screenshot

### ISSUE THREAD

**Issue by esprush** [responsively-org/responsively-app#309]
**Issue:** 
When taking screenshot for all devices. the screenshot folder opens for each device.

**Expectation:**
folder should open only once.

**Affects:** 
Linux

**Comment by Mattlomet** [comment]
Hello this issue seems to have been fixed. Just tested and only 1 folder opened for 4 devices.

**Comment by jjavierdguezas** [comment]
hi @Mattlomet did you test it on Windows? or did you test it on another OS?

**Comment by Mattlomet** [comment]
I tested it on Pop!_OS 20.04 LTS. Which is built on top of Ubuntu -- I'm unsure what linux distro the original comment was made about.

**Comment by jjavierdguezas** [comment]
Oh sorry I didn't see the Linux part in the original comment 😅 
should we close this @manojVivek @esprush @jzabala ?

**Comment by jjavierdguezas** [comment]
Sorry @Mattlomet I just tested it on Ubuntu using last AppImage and this still happen
OS Info:
>Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Responsively Info:
>Version: 0.12.0
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-117-generic

The code always opens the folder of the image created per device, the thing is how the file manager handles this kind of scenario (sequential calls to open the same path). In Windows, the explorer just focuses and blinks its icon on the taskbar (and gives the illusion that it was opened once). In Ubuntu, with the default file manager, a new window opens per device (this issue). Maybe your OS file manager handles this like Windows

**Comment by Mattlomet** [comment]
So upon further testing - 
(I am using the AppImage aswell)

**With User Preferences side bar open // or any other side bar for that matter**
I get the result that you are talking about - A separate file manager per device.


**Without any side bar open**
I get the my result that I had mentioned where it seems to be working properly at least on (PopOs/Ubuntu 20.04)


not sure really what to make of this just thought I'd put this out there for further debugging purposes

**Comment by jjavierdguezas** [comment]
I see the same behavior regardless of the drawer (sidebar) state

**Comment by GAURAV1-ui** [comment]
Hey @Hooman-Asbaghi can I work on this issue?

**Comment by sonu-deshwal** [comment]
I am half way done solution for this problem...if possible kindly assign task to me

**Comment by ArchitGajjar** [comment]
Hi @jjavierdguezas  - is this issue resolved, can I work on this ?

**Comment by jjavierdguezas** [comment]
> Hi @jjavierdguezas  - is this issue resolved, can I work on this ?

hi, I really don't know, I've been away from the project for some time now. 😓

could you help here @manojVivek ?

thanks

**Comment by manojVivek** [comment]
Yes, sorry this is already resolved, not an issue any more.
