### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by MrSnoozles** [responsively-org/responsively-app#835]
# 🐞 bug report

### ✍️ Description

Shortcuts (Ctrl+R for reload, F12 for DevTools) are not working. Nothing happens when they are pressed. F1 (environment info) works.

### 🕵🏼‍♂️ Is this a regression?

Yes

### 🔬 Minimal Reproduction

Do

### 🌍 Your Environment

<pre><code>
Version: 1.0.3
Electron: 23.1.0
Chrome: 110.0.5481.100
Node.js: 18.12.1
V8: 11.0.226.16-electron.0
OS: Windows_NT x64 10.0.19045
</code></pre>

**Comment by akshitd11** [comment]
Is this issue still persist, if yes can I take this up.

**Comment by manojVivek** [comment]
@akshitd11 Yes, please go ahead! 👍🏼

**Comment by akshitd11** [comment]
@manojVivek The issue is already fixed as for the reload part and dev tools have been assigned new shortcut. Though on my build the file menu was not working.

**Comment by manojVivek** [comment]
@akshitd11 Thanks for checking this, would it be possible for you to map `F12` as well as a shortcut to open the devtools?

**Comment by akshitd11** [comment]
Sure, I will take this issue.

**Comment by eigenstil** [comment]
Ctrl + R and F12 are still not working in the newest version:

- Version 1.7.0
- Electron 25.2.0
- Chrome 114.0.5735.134
- Node.js 18.15.0
- V8 11.4.183.23-eletrcon.0
- Windows_NT x64 10.0.22621
